# Generated by Django 4.0.4 on 2022-06-06 12:08

import api.v1.blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(max_length=4000, verbose_name='content')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.v1.blog.models.upload_image, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='published at')),
                ('views_count', models.IntegerField(blank=True, default=0, editable=False, null=True, verbose_name='views count')),
                ('active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='active')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, null=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author')),
            ],
            options={
                'verbose_name': 'blog',
                'verbose_name_plural': 'blogs',
                'db_table': 'blog',
                'ordering': ('-published_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=25, null=True, verbose_name='name')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='code')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='updated at')),
                ('active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Language',
                'db_table': 'language',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('content', models.TextField(max_length=4000, verbose_name='content')),
                ('active', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='active')),
                ('categories', models.ManyToManyField(blank=True, to='blog.category', verbose_name='categories')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_lan', to='blog.language', verbose_name='language')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_lang', to='blog.blog', verbose_name='post')),
            ],
            options={
                'verbose_name': 'PostLanguage',
                'verbose_name_plural': 'PostLanguages',
                'db_table': 'post_language',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(blank=True, to='blog.category', verbose_name='categories'),
        ),
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.language', verbose_name='language'),
        ),
    ]
