# Generated by Django 3.2.6 on 2022-06-07 02:43

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_postlanguage_content'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts_lang', to='blog.language', verbose_name='language'),
        ),
    ]
