# Generated by Django 3.2.6 on 2022-06-09 20:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20220609_1707'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='language',
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='language',
            field=models.CharField(max_length=10, verbose_name='language'),
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
