# Generated by Django 3.2.6 on 2022-06-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20220610_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlanguage',
            name='categories',
        ),
    ]
