# Generated by Django 3.2.6 on 2022-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_postlanguage_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlanguage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('uz', 'Uzbek'), ('ru', 'Russian')], default='en', max_length=2),
        ),
    ]
